// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: BJ25 Dash Display

#ifndef _BJ25_DASH_DISPLAY_UI_H
#define _BJ25_DASH_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


// SCREEN: ui_RACE_SCREEN
void ui_RACE_SCREEN_screen_init(void);
extern lv_obj_t * ui_RACE_SCREEN;
extern lv_obj_t * ui_SYSTEM_MESSAGE;
extern lv_obj_t * ui_MESSAGE;
extern lv_obj_t * ui_CVT_TEMP;
extern lv_obj_t * ui_CVT_TEMP_LABEL;
extern lv_obj_t * ui_CVT_TEMP_CELCIUS;
extern lv_obj_t * ui_FUEL;
extern lv_obj_t * ui_FUEL_LABEL;
extern lv_obj_t * ui_FUEL_LAPS_LABEL;
extern lv_obj_t * ui_FUEL_PERCENTAGE;
extern lv_obj_t * ui_LAPS_LEFT;
extern lv_obj_t * ui_LAPS;
extern lv_obj_t * ui_LAPS_LABEL;
extern lv_obj_t * ui_NUMBER_OF_LAPS;
extern lv_obj_t * ui_TBD;
extern lv_obj_t * ui_RPM_SPEED;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_SPEED;
extern lv_obj_t * ui_LOGO_BAJA;
extern lv_obj_t * ui_TBD_2;
extern lv_obj_t * ui_RUN_TIME;
extern lv_obj_t * ui_RUNNING_TIME;
extern lv_obj_t * ui_HEURE;
extern lv_obj_t * ui_HEURE_LOCALE;
extern lv_obj_t * ui_DIFF;
extern lv_obj_t * ui_DIFF_LABEL;
extern lv_obj_t * ui_DIFF_TIME;
extern lv_obj_t * ui_CURR;
extern lv_obj_t * ui_CURR_LABEL;
extern lv_obj_t * ui_CURR_TIME;
extern lv_obj_t * ui_LAST;
extern lv_obj_t * ui_LAST_LABEL;
extern lv_obj_t * ui_LAST_TIME;
extern lv_obj_t * ui_BEST;
extern lv_obj_t * ui_BEST_LABEL;
extern lv_obj_t * ui_BEST_TIME;
extern lv_obj_t * ui_TBD_3;
extern lv_obj_t * ui_TBD_3_LABEL;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_170713928);    // assets/LIGHT - BAJA UdeS Logo-03.png

// FONTS
LV_FONT_DECLARE(ui_font_Roboto_Black_100);
LV_FONT_DECLARE(ui_font_Roboto_Black_24);
LV_FONT_DECLARE(ui_font_Roboto_Black_30);
LV_FONT_DECLARE(ui_font_Roboto_Black_36);
LV_FONT_DECLARE(ui_font_Roboto_Black_42);
LV_FONT_DECLARE(ui_font_Roboto_Black_48);
LV_FONT_DECLARE(ui_font_Roboto_Black_60);
LV_FONT_DECLARE(ui_font_Roboto_Black_80);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
