// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: BJ25 Dash Display

#ifndef _UI_COMP_BACKGROUND_H
#define _UI_COMP_BACKGROUND_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Background
#define UI_COMP_BACKGROUND_BACKGROUND 0
#define _UI_COMP_BACKGROUND_NUM 1
lv_obj_t * ui_Background_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
