// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: BJ25 Dash Display

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_RACE_SCREEN
void ui_RACE_SCREEN_screen_init(void);
lv_obj_t * ui_RACE_SCREEN;
lv_obj_t * ui_SYSTEM_MESSAGE;
lv_obj_t * ui_MESSAGE;
lv_obj_t * ui_CVT_TEMP;
lv_obj_t * ui_CVT_TEMP_LABEL;
lv_obj_t * ui_CVT_TEMP_CELCIUS;
lv_obj_t * ui_FUEL;
lv_obj_t * ui_FUEL_LABEL;
lv_obj_t * ui_FUEL_LAPS_LABEL;
lv_obj_t * ui_FUEL_PERCENTAGE;
lv_obj_t * ui_LAPS_LEFT;
lv_obj_t * ui_LAPS;
lv_obj_t * ui_LAPS_LABEL;
lv_obj_t * ui_NUMBER_OF_LAPS;
lv_obj_t * ui_TBD;
lv_obj_t * ui_RPM_SPEED;
lv_obj_t * ui_RPM;
lv_obj_t * ui_SPEED;
lv_obj_t * ui_LOGO_BAJA;
lv_obj_t * ui_TBD_2;
lv_obj_t * ui_RUN_TIME;
lv_obj_t * ui_RUNNING_TIME;
lv_obj_t * ui_HEURE;
lv_obj_t * ui_HEURE_LOCALE;
lv_obj_t * ui_DIFF;
lv_obj_t * ui_DIFF_LABEL;
lv_obj_t * ui_DIFF_TIME;
lv_obj_t * ui_CURR;
lv_obj_t * ui_CURR_LABEL;
lv_obj_t * ui_CURR_TIME;
lv_obj_t * ui_LAST;
lv_obj_t * ui_LAST_LABEL;
lv_obj_t * ui_LAST_TIME;
lv_obj_t * ui_BEST;
lv_obj_t * ui_BEST_LABEL;
lv_obj_t * ui_BEST_TIME;
lv_obj_t * ui_TBD_3;
lv_obj_t * ui_TBD_3_LABEL;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_RACE_SCREEN_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_RACE_SCREEN);
}
