// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: BJ25 Dash Display

#include "ui.h"

void ui_RACE_SCREEN_screen_init(void)
{
    ui_RACE_SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RACE_SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RACE_SCREEN, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RACE_SCREEN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SYSTEM_MESSAGE = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_SYSTEM_MESSAGE);
    lv_obj_set_width(ui_SYSTEM_MESSAGE, 790);
    lv_obj_set_height(ui_SYSTEM_MESSAGE, 75);
    lv_obj_set_x(ui_SYSTEM_MESSAGE, 0);
    lv_obj_set_y(ui_SYSTEM_MESSAGE, -200);
    lv_obj_set_align(ui_SYSTEM_MESSAGE, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SYSTEM_MESSAGE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SYSTEM_MESSAGE, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SYSTEM_MESSAGE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SYSTEM_MESSAGE, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SYSTEM_MESSAGE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SYSTEM_MESSAGE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SYSTEM_MESSAGE, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MESSAGE = lv_label_create(ui_SYSTEM_MESSAGE);
    lv_obj_set_width(ui_MESSAGE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MESSAGE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MESSAGE, 25);
    lv_obj_set_y(ui_MESSAGE, 1);
    lv_obj_set_align(ui_MESSAGE, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MESSAGE, "MESSAGE SYSTEME");
    lv_obj_set_style_text_color(ui_MESSAGE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MESSAGE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MESSAGE, &ui_font_Roboto_Black_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CVT_TEMP = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_CVT_TEMP);
    lv_obj_set_width(ui_CVT_TEMP, 310);
    lv_obj_set_height(ui_CVT_TEMP, 128);
    lv_obj_set_x(ui_CVT_TEMP, -240);
    lv_obj_set_y(ui_CVT_TEMP, -93);
    lv_obj_set_align(ui_CVT_TEMP, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CVT_TEMP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CVT_TEMP, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CVT_TEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CVT_TEMP_LABEL = lv_label_create(ui_CVT_TEMP);
    lv_obj_set_width(ui_CVT_TEMP_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CVT_TEMP_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CVT_TEMP_LABEL, 25);
    lv_obj_set_y(ui_CVT_TEMP_LABEL, 26);
    lv_label_set_text(ui_CVT_TEMP_LABEL, "CVT TEMP");
    lv_obj_set_style_text_font(ui_CVT_TEMP_LABEL, &ui_font_Roboto_Black_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CVT_TEMP_CELCIUS = lv_label_create(ui_CVT_TEMP);
    lv_obj_set_width(ui_CVT_TEMP_CELCIUS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CVT_TEMP_CELCIUS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CVT_TEMP_CELCIUS, 25);
    lv_obj_set_y(ui_CVT_TEMP_CELCIUS, -15);
    lv_obj_set_align(ui_CVT_TEMP_CELCIUS, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_CVT_TEMP_CELCIUS, "65");
    lv_obj_set_style_text_font(ui_CVT_TEMP_CELCIUS, &ui_font_Roboto_Black_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUEL = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_FUEL);
    lv_obj_set_width(ui_FUEL, 310);
    lv_obj_set_height(ui_FUEL, 128);
    lv_obj_set_x(ui_FUEL, -240);
    lv_obj_set_y(ui_FUEL, 40);
    lv_obj_set_align(ui_FUEL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FUEL, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FUEL, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FUEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUEL_LABEL = lv_label_create(ui_FUEL);
    lv_obj_set_width(ui_FUEL_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUEL_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUEL_LABEL, 25);
    lv_obj_set_y(ui_FUEL_LABEL, 26);
    lv_label_set_text(ui_FUEL_LABEL, "FUEL");
    lv_obj_set_style_text_font(ui_FUEL_LABEL, &ui_font_Roboto_Black_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUEL_LAPS_LABEL = lv_label_create(ui_FUEL);
    lv_obj_set_width(ui_FUEL_LAPS_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUEL_LAPS_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUEL_LAPS_LABEL, 58);
    lv_obj_set_y(ui_FUEL_LAPS_LABEL, 26);
    lv_obj_set_align(ui_FUEL_LAPS_LABEL, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_FUEL_LAPS_LABEL, "LAPS LEFT");
    lv_obj_set_style_text_font(ui_FUEL_LAPS_LABEL, &ui_font_Roboto_Black_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUEL_PERCENTAGE = lv_label_create(ui_FUEL);
    lv_obj_set_width(ui_FUEL_PERCENTAGE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUEL_PERCENTAGE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUEL_PERCENTAGE, 25);
    lv_obj_set_y(ui_FUEL_PERCENTAGE, -15);
    lv_obj_set_align(ui_FUEL_PERCENTAGE, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_FUEL_PERCENTAGE, "42.9");
    lv_obj_set_style_text_font(ui_FUEL_PERCENTAGE, &ui_font_Roboto_Black_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAPS_LEFT = lv_label_create(ui_FUEL);
    lv_obj_set_width(ui_LAPS_LEFT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LAPS_LEFT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LAPS_LEFT, 180);
    lv_obj_set_y(ui_LAPS_LEFT, -15);
    lv_obj_set_align(ui_LAPS_LEFT, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LAPS_LEFT, "15");
    lv_obj_set_style_text_font(ui_LAPS_LEFT, &ui_font_Roboto_Black_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAPS = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_LAPS);
    lv_obj_set_width(ui_LAPS, 152);
    lv_obj_set_height(ui_LAPS, 128);
    lv_obj_set_x(ui_LAPS, -161);
    lv_obj_set_y(ui_LAPS, 173);
    lv_obj_set_align(ui_LAPS, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LAPS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LAPS, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LAPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LAPS, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LAPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LAPS, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LAPS, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAPS_LABEL = lv_label_create(ui_LAPS);
    lv_obj_set_width(ui_LAPS_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LAPS_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LAPS_LABEL, 25);
    lv_obj_set_y(ui_LAPS_LABEL, 26);
    lv_label_set_text(ui_LAPS_LABEL, "LAPS");
    lv_obj_set_style_text_font(ui_LAPS_LABEL, &ui_font_Roboto_Black_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NUMBER_OF_LAPS = lv_label_create(ui_LAPS);
    lv_obj_set_width(ui_NUMBER_OF_LAPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NUMBER_OF_LAPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NUMBER_OF_LAPS, 25);
    lv_obj_set_y(ui_NUMBER_OF_LAPS, -15);
    lv_obj_set_align(ui_NUMBER_OF_LAPS, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_NUMBER_OF_LAPS, "3");
    lv_obj_set_style_text_font(ui_NUMBER_OF_LAPS, &ui_font_Roboto_Black_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TBD = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_TBD);
    lv_obj_set_width(ui_TBD, 153);
    lv_obj_set_height(ui_TBD, 128);
    lv_obj_set_x(ui_TBD, -319);
    lv_obj_set_y(ui_TBD, 173);
    lv_obj_set_align(ui_TBD, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TBD, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TBD, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TBD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TBD, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TBD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TBD, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TBD, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM_SPEED = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_RPM_SPEED);
    lv_obj_set_width(ui_RPM_SPEED, 160);
    lv_obj_set_height(ui_RPM_SPEED, 203);
    lv_obj_set_x(ui_RPM_SPEED, 0);
    lv_obj_set_y(ui_RPM_SPEED, -56);
    lv_obj_set_align(ui_RPM_SPEED, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPM_SPEED, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RPM_SPEED, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM_SPEED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM = lv_label_create(ui_RPM_SPEED);
    lv_obj_set_width(ui_RPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPM, 0);
    lv_obj_set_y(ui_RPM, 15);
    lv_obj_set_align(ui_RPM, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_RPM, "2998");
    lv_obj_set_style_text_font(ui_RPM, &ui_font_Roboto_Black_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPEED = lv_label_create(ui_RPM_SPEED);
    lv_obj_set_width(ui_SPEED, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPEED, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SPEED, 0);
    lv_obj_set_y(ui_SPEED, -10);
    lv_obj_set_align(ui_SPEED, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SPEED, "58");
    lv_obj_set_style_text_font(ui_SPEED, &ui_font_Roboto_Black_100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LOGO_BAJA = lv_img_create(ui_RACE_SCREEN);
    lv_img_set_src(ui_LOGO_BAJA, &ui_img_170713928);
    lv_obj_set_width(ui_LOGO_BAJA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LOGO_BAJA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LOGO_BAJA, 0);
    lv_obj_set_y(ui_LOGO_BAJA, 96);
    lv_obj_set_align(ui_LOGO_BAJA, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LOGO_BAJA, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_LOGO_BAJA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LOGO_BAJA, 75);

    ui_TBD_2 = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_TBD_2);
    lv_obj_set_width(ui_TBD_2, 160);
    lv_obj_set_height(ui_TBD_2, 91);
    lv_obj_set_x(ui_TBD_2, 0);
    lv_obj_set_y(ui_TBD_2, 96);
    lv_obj_set_align(ui_TBD_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TBD_2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TBD_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TBD_2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TBD_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RUN_TIME = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_RUN_TIME);
    lv_obj_set_width(ui_RUN_TIME, 160);
    lv_obj_set_height(ui_RUN_TIME, 43);
    lv_obj_set_x(ui_RUN_TIME, 0);
    lv_obj_set_y(ui_RUN_TIME, 168);
    lv_obj_set_align(ui_RUN_TIME, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RUN_TIME, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RUN_TIME, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RUN_TIME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RUNNING_TIME = lv_label_create(ui_RUN_TIME);
    lv_obj_set_width(ui_RUNNING_TIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RUNNING_TIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RUNNING_TIME, 0);
    lv_obj_set_y(ui_RUNNING_TIME, 1);
    lv_obj_set_align(ui_RUNNING_TIME, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RUNNING_TIME, "00:03:37");
    lv_obj_set_style_text_font(ui_RUNNING_TIME, &ui_font_Roboto_Black_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HEURE = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_HEURE);
    lv_obj_set_width(ui_HEURE, 160);
    lv_obj_set_height(ui_HEURE, 43);
    lv_obj_set_x(ui_HEURE, 0);
    lv_obj_set_y(ui_HEURE, 216);
    lv_obj_set_align(ui_HEURE, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HEURE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HEURE, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HEURE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HEURE, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HEURE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HEURE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HEURE, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HEURE_LOCALE = lv_label_create(ui_HEURE);
    lv_obj_set_width(ui_HEURE_LOCALE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HEURE_LOCALE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HEURE_LOCALE, 0);
    lv_obj_set_y(ui_HEURE_LOCALE, 1);
    lv_obj_set_align(ui_HEURE_LOCALE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HEURE_LOCALE, "14:37");
    lv_obj_set_style_text_font(ui_HEURE_LOCALE, &ui_font_Roboto_Black_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_DIFF);
    lv_obj_set_width(ui_DIFF, 310);
    lv_obj_set_height(ui_DIFF, 75);
    lv_obj_set_x(ui_DIFF, 240);
    lv_obj_set_y(ui_DIFF, -120);
    lv_obj_set_align(ui_DIFF, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DIFF, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DIFF, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DIFF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF_LABEL = lv_label_create(ui_DIFF);
    lv_obj_set_width(ui_DIFF_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIFF_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIFF_LABEL, 25);
    lv_obj_set_y(ui_DIFF_LABEL, 1);
    lv_obj_set_align(ui_DIFF_LABEL, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DIFF_LABEL, "DIFF");
    lv_obj_set_style_text_font(ui_DIFF_LABEL, &ui_font_Roboto_Black_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF_TIME = lv_label_create(ui_DIFF);
    lv_obj_set_width(ui_DIFF_TIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIFF_TIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIFF_TIME, -25);
    lv_obj_set_y(ui_DIFF_TIME, 1);
    lv_obj_set_align(ui_DIFF_TIME, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DIFF_TIME, "-6.74");
    lv_obj_set_style_text_color(ui_DIFF_TIME, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIFF_TIME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIFF_TIME, &ui_font_Roboto_Black_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CURR = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_CURR);
    lv_obj_set_width(ui_CURR, 310);
    lv_obj_set_height(ui_CURR, 75);
    lv_obj_set_x(ui_CURR, 240);
    lv_obj_set_y(ui_CURR, -40);
    lv_obj_set_align(ui_CURR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CURR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CURR, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CURR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CURR_LABEL = lv_label_create(ui_CURR);
    lv_obj_set_width(ui_CURR_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CURR_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CURR_LABEL, 25);
    lv_obj_set_y(ui_CURR_LABEL, 1);
    lv_obj_set_align(ui_CURR_LABEL, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CURR_LABEL, "CURR");
    lv_obj_set_style_text_font(ui_CURR_LABEL, &ui_font_Roboto_Black_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CURR_TIME = lv_label_create(ui_CURR);
    lv_obj_set_width(ui_CURR_TIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CURR_TIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CURR_TIME, -25);
    lv_obj_set_y(ui_CURR_TIME, 1);
    lv_obj_set_align(ui_CURR_TIME, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_CURR_TIME, "00:03,370");
    lv_obj_set_style_text_font(ui_CURR_TIME, &ui_font_Roboto_Black_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAST = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_LAST);
    lv_obj_set_width(ui_LAST, 310);
    lv_obj_set_height(ui_LAST, 75);
    lv_obj_set_x(ui_LAST, 240);
    lv_obj_set_y(ui_LAST, 40);
    lv_obj_set_align(ui_LAST, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LAST, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LAST, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LAST, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAST_LABEL = lv_label_create(ui_LAST);
    lv_obj_set_width(ui_LAST_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LAST_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LAST_LABEL, 25);
    lv_obj_set_y(ui_LAST_LABEL, 1);
    lv_obj_set_align(ui_LAST_LABEL, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LAST_LABEL, "LAST");
    lv_obj_set_style_text_font(ui_LAST_LABEL, &ui_font_Roboto_Black_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAST_TIME = lv_label_create(ui_LAST);
    lv_obj_set_width(ui_LAST_TIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LAST_TIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LAST_TIME, -25);
    lv_obj_set_y(ui_LAST_TIME, 1);
    lv_obj_set_align(ui_LAST_TIME, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LAST_TIME, "01:07,072");
    lv_obj_set_style_text_font(ui_LAST_TIME, &ui_font_Roboto_Black_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BEST = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_BEST);
    lv_obj_set_width(ui_BEST, 310);
    lv_obj_set_height(ui_BEST, 75);
    lv_obj_set_x(ui_BEST, 240);
    lv_obj_set_y(ui_BEST, 120);
    lv_obj_set_align(ui_BEST, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BEST, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BEST, lv_color_hex(0x4E0B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BEST, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BEST_LABEL = lv_label_create(ui_BEST);
    lv_obj_set_width(ui_BEST_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BEST_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BEST_LABEL, 25);
    lv_obj_set_y(ui_BEST_LABEL, 1);
    lv_obj_set_align(ui_BEST_LABEL, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BEST_LABEL, "BEST");
    lv_obj_set_style_text_font(ui_BEST_LABEL, &ui_font_Roboto_Black_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BEST_TIME = lv_label_create(ui_BEST);
    lv_obj_set_width(ui_BEST_TIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BEST_TIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BEST_TIME, -25);
    lv_obj_set_y(ui_BEST_TIME, 1);
    lv_obj_set_align(ui_BEST_TIME, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BEST_TIME, "00:57,423");
    lv_obj_set_style_text_font(ui_BEST_TIME, &ui_font_Roboto_Black_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TBD_3 = lv_obj_create(ui_RACE_SCREEN);
    lv_obj_remove_style_all(ui_TBD_3);
    lv_obj_set_width(ui_TBD_3, 310);
    lv_obj_set_height(ui_TBD_3, 75);
    lv_obj_set_x(ui_TBD_3, 240);
    lv_obj_set_y(ui_TBD_3, 200);
    lv_obj_set_align(ui_TBD_3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TBD_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TBD_3, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TBD_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TBD_3, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TBD_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TBD_3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TBD_3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TBD_3_LABEL = lv_label_create(ui_TBD_3);
    lv_obj_set_width(ui_TBD_3_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TBD_3_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TBD_3_LABEL, 25);
    lv_obj_set_y(ui_TBD_3_LABEL, 1);
    lv_obj_set_align(ui_TBD_3_LABEL, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TBD_3_LABEL, "TBD 3");
    lv_obj_add_flag(ui_TBD_3_LABEL, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_TBD_3_LABEL, &ui_font_Roboto_Black_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
